/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const JobCategory = IDL.Variant({
  'ssc' : IDL.Null,
  'railway' : IDL.Null,
  'upsc' : IDL.Null,
  'banking' : IDL.Null,
  'teaching' : IDL.Null,
  'centralGovernment' : IDL.Null,
  'defence' : IDL.Null,
  'stateGovernment' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const JobPost = IDL.Record({
  'id' : IDL.Nat,
  'jobCategory' : JobCategory,
  'orgName' : IDL.Text,
  'applyLink' : IDL.Text,
  'totalVacancies' : IDL.Nat,
  'notificationPdf' : IDL.Opt(ExternalBlob),
  'jobTitle' : IDL.Text,
  'lastDate' : IDL.Text,
  'qualification' : IDL.Text,
  'location' : IDL.Text,
});
export const ServicePricing = IDL.Record({
  'serviceName' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'isVisible' : IDL.Bool,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        JobCategory,
      ],
      [IDL.Nat],
      [],
    ),
  'addServicePricing' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteContactSubmission' : IDL.Func([IDL.Nat], [], []),
  'deleteJobPost' : IDL.Func([IDL.Nat], [], []),
  'deleteServicePricing' : IDL.Func([IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'enableCategory' : IDL.Func([JobCategory, IDL.Bool], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllCategoryStates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(JobCategory, IDL.Bool))],
      ['query'],
    ),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
  'getAllServicePricing' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ServicePricing))],
      ['query'],
    ),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryState' : IDL.Func([JobCategory], [IDL.Bool], ['query']),
  'getJobPost' : IDL.Func([IDL.Nat], [IDL.Opt(JobPost)], ['query']),
  'getJobsByCategory' : IDL.Func([JobCategory], [IDL.Vec(JobPost)], ['query']),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisibleTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(JobPost)], ['query']),
  'setBlogPostPublished' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateBlogPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'updateJobPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        JobCategory,
      ],
      [],
      [],
    ),
  'updateServicePricing' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTestimonial' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const JobCategory = IDL.Variant({
    'ssc' : IDL.Null,
    'railway' : IDL.Null,
    'upsc' : IDL.Null,
    'banking' : IDL.Null,
    'teaching' : IDL.Null,
    'centralGovernment' : IDL.Null,
    'defence' : IDL.Null,
    'stateGovernment' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const JobPost = IDL.Record({
    'id' : IDL.Nat,
    'jobCategory' : JobCategory,
    'orgName' : IDL.Text,
    'applyLink' : IDL.Text,
    'totalVacancies' : IDL.Nat,
    'notificationPdf' : IDL.Opt(ExternalBlob),
    'jobTitle' : IDL.Text,
    'lastDate' : IDL.Text,
    'qualification' : IDL.Text,
    'location' : IDL.Text,
  });
  const ServicePricing = IDL.Record({
    'serviceName' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'isVisible' : IDL.Bool,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          JobCategory,
        ],
        [IDL.Nat],
        [],
      ),
    'addServicePricing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteContactSubmission' : IDL.Func([IDL.Nat], [], []),
    'deleteJobPost' : IDL.Func([IDL.Nat], [], []),
    'deleteServicePricing' : IDL.Func([IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'enableCategory' : IDL.Func([JobCategory, IDL.Bool], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllCategoryStates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(JobCategory, IDL.Bool))],
        ['query'],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
    'getAllServicePricing' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ServicePricing))],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryState' : IDL.Func([JobCategory], [IDL.Bool], ['query']),
    'getJobPost' : IDL.Func([IDL.Nat], [IDL.Opt(JobPost)], ['query']),
    'getJobsByCategory' : IDL.Func(
        [JobCategory],
        [IDL.Vec(JobPost)],
        ['query'],
      ),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisibleTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(JobPost)], ['query']),
    'setBlogPostPublished' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateJobPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          JobCategory,
        ],
        [],
        [],
      ),
    'updateServicePricing' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTestimonial' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };