/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : Time,
  'updatedAt' : Time,
}
export interface ContactFormSubmission {
  'id' : bigint,
  'name' : string,
  'submittedAt' : Time,
  'message' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export type JobCategory = { 'ssc' : null } |
  { 'railway' : null } |
  { 'upsc' : null } |
  { 'banking' : null } |
  { 'teaching' : null } |
  { 'centralGovernment' : null } |
  { 'defence' : null } |
  { 'stateGovernment' : null };
export interface JobPost {
  'id' : bigint,
  'jobCategory' : JobCategory,
  'orgName' : string,
  'applyLink' : string,
  'totalVacancies' : bigint,
  'notificationPdf' : [] | [ExternalBlob],
  'jobTitle' : string,
  'lastDate' : string,
  'qualification' : string,
  'location' : string,
}
export interface ServicePricing {
  'serviceName' : string,
  'description' : string,
  'price' : string,
}
export interface Testimonial {
  'id' : bigint,
  'content' : string,
  'name' : string,
  'isVisible' : boolean,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJobPost' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      JobCategory,
    ],
    bigint
  >,
  'addServicePricing' : ActorMethod<[string, string, string], bigint>,
  'addTestimonial' : ActorMethod<[string, string, bigint, boolean], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[string, string, boolean], bigint>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteContactSubmission' : ActorMethod<[bigint], undefined>,
  'deleteJobPost' : ActorMethod<[bigint], undefined>,
  'deleteServicePricing' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'enableCategory' : ActorMethod<[JobCategory, boolean], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllCategoryStates' : ActorMethod<[], Array<[JobCategory, boolean]>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllJobPosts' : ActorMethod<[], Array<JobPost>>,
  'getAllServicePricing' : ActorMethod<[], Array<[bigint, ServicePricing]>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryState' : ActorMethod<[JobCategory], boolean>,
  'getJobPost' : ActorMethod<[bigint], [] | [JobPost]>,
  'getJobsByCategory' : ActorMethod<[JobCategory], Array<JobPost>>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisibleTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchJobs' : ActorMethod<[string], Array<JobPost>>,
  'setBlogPostPublished' : ActorMethod<[bigint, boolean], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'updateBlogPost' : ActorMethod<[bigint, string, string, boolean], undefined>,
  'updateJobPost' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      JobCategory,
    ],
    undefined
  >,
  'updateServicePricing' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];